blueprint:
  name: "Fully Kiosk – Streaming Bildschirmtimer aus"
  description: "Setzt das Display-Timeout auf 0, sobald eine ausgewählte Streaming-App im Vordergrund läuft."
  domain: automation
  source_url: https://github.com/23Phantom08/Home-Assistant-Blueprint/blob/main/blueprints/fully_kiosk_streaming_timeout_off.yaml
  input:
    app_sensor:
      name: Vordergrund-App Sensor
      selector:
        entity:
          domain: sensor
    timeout_entity:
      name: Bildschirm Timeout Entität
      selector:
        entity:
          domain: number
    streaming_apps:
      name: Streaming-Apps
      description: "Liste der Apps, die den Bildschirm eingeschaltet halten sollen"
      default:
        - "com.netflix.mediaclient"
        - "com.disney.disneyplus"
        - "com.amazon.avod"
        - "de.sky.online"
        - "org.jellyfin.mobile"
        - "com.einsundeinstv.player"
        - "com.amazon.mp3"
      selector:
        select:
          multiple: true
          custom_value: true # Erlaubt dem Nutzer, eigene Paketnamen einzutippen
          options:
            - com.netflix.mediaclient
            - com.disney.disneyplus
            - com.amazon.avod
            - de.sky.online
            - org.jellyfin.mobile
            - com.einsundeinstv.player
            - com.amazon.mp3

trigger:
  - platform: state
    entity_id: !input app_sensor
    to: !input streaming_apps

action:
  - action: number.set_value 
    target:
      entity_id: !input timeout_entity
    data:
      value: 0

mode: single





