blueprint:
  name: "Fully Kiosk – Streaming Bildschirmtimer an"
  description: "Stellt das Display-Timeout wieder her, wenn die App verlassen wird."
  domain: automation
  author: Mario Tamme
  source_url: https://github.com
  input:
    app_sensor:
      name: Vordergrund-App Sensor
      selector:
        entity:
          domain: sensor
    timeout_entity:
      name: Bildschirm Timeout Entität
      selector:
        entity:
          domain: number
    restore_value:
      name: Timeout-Wert (Sekunden)
      default: 80
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: "s"
          mode: box
    netflix_pkg:
      name: Netflix Paketname
      default: "com.netflix.mediaclient"
    disney_pkg:
      name: Disney+ Paketname
      default: "com.disney.disneyplus"
    prime_pkg:
      name: Amazon Prime Paketname
      default: "com.amazon.avod.thirdpartyclient"
    wow_pkg:
      name: WOW Paketname
      default: "de.sky.online"

variables:
  n_pkg: !input netflix_pkg
  d_pkg: !input disney_pkg
  p_pkg: !input prime_pkg
  w_pkg: !input wow_pkg
  t_ent: !input timeout_entity

trigger:
  - platform: state
    entity_id: !input app_sensor

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.state not in [n_pkg, d_pkg, p_pkg, w_pkg, 'unknown', 'unavailable'] }}
  - condition: template
    value_template: "{{ is_state(t_ent, '0') }}"

action:
  - action: number.set_value
    target:
      entity_id: !input timeout_entity
    data:
      value: !input restore_value

mode: single
